version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
  web:
    build: .
    image: nyc_collision
    command: python manage.py runserver 0.0.0.0:8000 
    volumes:
      - .:/vehicle_collisions
    ports:
      - "8000:8000"
    depends_on:
      - migration
      - db
  migration:
    image: nyc_collision
    command: python manage.py migrate --noinput
    volumes:
      - .:/vehicle_collisions
    depends_on:
      - db