# Generated by Django 3.1.5 on 2021-02-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_collisions', '0003_auto_20210201_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citibikestation',
            name='id',
        ),
        migrations.AlterField(
            model_name='citibikestation',
            name='station_id',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
    ]
