# Generated by Django 3.1.5 on 2021-02-02 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_collisions', '0004_auto_20210201_2119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CitiBikeStation',
        ),
    ]
