# Generated by Django 3.1.5 on 2021-02-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_collisions', '0005_delete_citibikestation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitiBikeStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.FloatField()),
                ('station_name', models.CharField(max_length=100)),
                ('station_latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('station_longitude', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
    ]
